### ISSUE TITLE
Fix font bug on load

### ISSUE THREAD

**Issue by fzn0x** [fzn0x/mazer-nuxt#307]
This bug causing the font unloaded

```sh
 ERROR  body used already for: https://fonts.googleapis.com/css2?family=Nunito&display=swap                                                             nuxt:google-fonts 17:14:31

  at consumeBody (/D:/Projects/mazer-nuxt/node_modules/.pnpm/node-fetch-native@0.1.8/node_modules/node-fetch-native/dist/shared/node-fetch-native.b703cef9.mjs:4976:9)
  at Response.text (/D:/Projects/mazer-nuxt/node_modules/.pnpm/node-fetch-native@0.1.8/node_modules/node-fetch-native/dist/shared/node-fetch-native.b703cef9.mjs:4938:24)
  at $fetchRaw2 (/D:/Projects/mazer-nuxt/node_modules/.pnpm/ohmyfetch@0.4.21/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:159:60)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Downloader.execute (/D:/Projects/mazer-nuxt/node_modules/.pnpm/google-fonts-helper@3.2.2/node_modules/google-fonts-helper/dist/index.mjs:171:24)
  at async setup (/D:/Projects/mazer-nuxt/node_modules/.pnpm/@nuxtjs+google-fonts@3.0.0-1_rollup@2.79.1/node_modules/@nuxtjs/google-fonts/dist/module.mjs:70:9)
  at async normalizedModule (/D:/Projects/mazer-nuxt/node_modules/.pnpm/@nuxt+kit@3.0.0_rollup@2.79.1/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (/D:/Projects/mazer-nuxt/node_modules/.pnpm/@nuxt+kit@3.0.0_rollup@2.79.1/node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (/D:/Projects/mazer-nuxt/node_modules/.pnpm/nuxt@3.0.0_rollup@2.79.1+sass@1.56.1/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/D:/Projects/mazer-nuxt/node_modules/.pnpm/nuxi@3.0.0/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
```

This is happen sometimes we run the nuxt server, and sometimes not. This is considered as a flaky bug,

**Comment by fzn0x** [comment]
After updating the deps, this flaky bug doesn't happen anymore
